name: flutter_funding_choices
description: The Flutter implementation of Funding Choices, a Google service that allows to request user consent for personalized ads in AdMob.
version: 0.3.0+2
homepage: https://github.com/Skyost/FlutterFundingChoices

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.fundingchoices
        pluginClass: FlutterFundingChoicesPlugin
      ios:
        pluginClass: FlutterFundingChoicesPlugin
