name: flutter_funding_choices
description: The Flutter implementation of Funding Choices, a Google service that allows to request user consent for personalized ads in AdMob.
version: 1.0.0
homepage: https://github.com/Skyost/FlutterFundingChoices

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fr.skyost.fundingchoices
        pluginClass: FlutterFundingChoicesPlugin
      ios:
        pluginClass: FlutterFundingChoicesPlugin
